name: Lint vscode-extension
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint-extension.yml'
      - 'vscode-extension/src/**'
  pull_request:
    paths:
      - '.github/workflows/lint-extension.yml'
      - 'vscode-extension/src/**'

jobs:
  check:
    if: github.repository == 'software-mansion-labs/react-native-sztudio'
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: vscode-extension
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: vscode-extension/package-lock.json

      - name: Install node dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm i

      - name: Lint extension
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run lint
